//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Finaktiva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class prueba_finaktiva_celsoEntities : DbContext
    {
        public prueba_finaktiva_celsoEntities()
            : base("name=prueba_finaktiva_celsoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<municipio> municipio { get; set; }
        public virtual DbSet<region> region { get; set; }
        public virtual DbSet<municipio_region> municipio_region { get; set; }
    }
}
